export const mockGPTResponses = {
  "hindi movies": ["DON", "Ravan", "Krish", "Sholay", "Gadar"],
  "comedy movies": ["Chupke Chupke", "Golmaal", "Bhool Bhulaiyaa", "Hungama", "Housefull"],
  "horror movies": ["Raaz", "Bhoot", "Stree", "Pari", "Tumbbad"],
  "action movies": ["War", "Singham", "Dhoom", "Rowdy Rathore", "Tiger Zinda Hai"],
  "romantic movies": ["Dilwale Dulhania Le Jayenge", "Kabir Singh", "Hum Dil De Chuke Sanam", "Aashiqui 2", "Yeh Jawaani Hai Deewani"],
  "thriller movies": ["Kahaani", "Drishyam", "Andhadhun", "Badla", "Talaash"],
  "drama movies": ["3 Idiots", "Taare Zameen Par", "Pad Man", "Bajrangi Bhaijaan", "Chhichhore"],
  "adventure movies": ["Ra.One", "Krrish 3", "Baahubali", "Jungle Book", "Koi Mil Gaya"],
  "family movies": ["Hum Saath Saath Hain", "Kabhi Khushi Kabhie Gham", "Bajrangi Bhaijaan", "Taare Zameen Par", "Paa"],
  "fantasy movies": ["Ra.One", "Koi Mil Gaya", "Tumbbad", "Krrish", "Paheli"],
  
  "english movies": ["Inception", "Titanic", "Avatar", "Interstellar", "The Dark Knight"],
  "english comedy movies": ["The Hangover", "Superbad", "Step Brothers", "Bridesmaids", "21 Jump Street"],
  "english horror movies": ["The Conjuring", "It", "Annabelle", "Hereditary", "A Quiet Place"],
  "english action movies": ["Avengers: Endgame", "Mad Max: Fury Road", "John Wick", "Gladiator", "Die Hard"],
  "english romantic movies": ["The Notebook", "Pride & Prejudice", "La La Land", "Titanic", "Romeo + Juliet"],
  "english thriller movies": ["Gone Girl", "Shutter Island", "Se7en", "Fight Club", "The Prestige"],
  "english drama movies": ["Forrest Gump", "The Godfather", "The Shawshank Redemption", "Parasite", "12 Years a Slave"],
  "english adventure movies": ["The Lord of the Rings", "Harry Potter", "Pirates of the Caribbean", "Jurassic Park", "Indiana Jones"],
  "english family movies": ["Finding Nemo", "The Lion King", "Toy Story", "Up", "Coco"],
  "english fantasy movies": ["Harry Potter", "The Hobbit", "The Chronicles of Narnia", "Fantastic Beasts", "Alice in Wonderland"],
  
  "animated movies": ["Frozen", "Moana", "Zootopia", "Big Hero 6", "Kung Fu Panda"],
  "kids movies": ["Despicable Me", "Shrek", "The Incredibles", "Trolls", "How to Train Your Dragon"],
  "sci-fi movies": ["Interstellar", "Blade Runner", "The Matrix", "Inception", "Arrival"],
  "superhero movies": ["Avengers: Endgame", "Spider-Man: No Way Home", "Black Panther", "Iron Man", "Wonder Woman"],
  "marvel movies": ["Iron Man", "Captain America", "Thor", "Guardians of the Galaxy", "Black Widow"],
  "dc movies": ["Wonder Woman", "Batman v Superman", "Aquaman", "Shazam!", "The Flash"],
  "classic movies": ["Casablanca", "Gone with the Wind", "Citizen Kane", "The Godfather", "Lawrence of Arabia"],
  "oscar winning movies": ["Parasite", "The Shape of Water", "Birdman", "12 Years a Slave", "The King’s Speech"],
  "netflix movies": ["Extraction", "The Old Guard", "Enola Holmes", "Bird Box", "The Gray Man"],
  "amazon prime movies": ["Borat Subsequent", "Coming 2 America", "The Tomorrow War", "Without Remorse", "Sound of Metal"]
};
